steps:
  # build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'ci-cd:latest', '-t', 'ci-cd:$SHORT_SHA', '.']

  # also can use only 'docker' as name, gcr will recognize too
  # run
  - name: 'docker'
    args: ['run', '-d', '--name', 'goapp', 'ci-cd:latest']

  # tests
  #- name: 'docker'
  #  args: ['exeg', 'goapp', 'go', 'test']

  #- name: 'docker'
  #  args: ['push', 'ci-cd:latest', 'ci-cd:$SHORT_SHA']
