steps:
  # build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "ci-cd:latest", "-t", "ci-cd:$SHORT_SHA", "."]

  # also can use only 'docker' as name, gcr will recognize too
  # run
  - name: "docker"
    args: ["run", "-d", "--name", "goapp", "ci-cd:latest"]

  # tests
  #- name: 'docker'
  #  args: ['exeg', 'goapp', 'go', 'test']

  # push do cloud run
  - name: "docker"
    args: ["push", "ci-cd:latest"]

  - name: "docker"
    args: ["push", "ci-cd:$SHORT_SHA"]

    # us-central1
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "go-cloudrun",
        "--image",
        "ci-cd:$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

