steps:
  # build
  - name: "docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/cloud-functions-estudo/ci-cd:latest",
        "-t",
        "gcr.io/cloud-functions-estudo/ci-cd:$SHORT_SHA",
        ".",
      ]
  # run
  - name: "docker"
    args:
      [
        "run",
        "-d",
        "--name",
        "goapp",
        "gcr.io/cloud-functions-estudo/ci-cd:latest",
      ]
  # test
  # - name: 'docker'
  #  args: ['exec', 'goapp', 'go', 'test']
