steps:
  # build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/cloud-functions-estudo/ci-cd:latest",
        "-t",
        "gcr.io/cloud-functions-estudo/ci-cd:$SHORT_SHA",
        ".",
      ]

  # also can use only 'docker' as name, gcr will recognize too
  # run
  - name: "docker"
    args:
      [
        "run",
        "-d",
        "--name",
        "goapp",
        "gcr.io/cloud-functions-estudo/ci-cd:latest",
      ]

  # tests
  #- name: 'docker'
  #  args: ['exeg', 'goapp', 'go', 'test']

  # push do cloud run
  - name: "docker"
    args: ["push", "gcr.io/cloud-functions-estudo/ci-cd:latest"]

  - name: "docker"
    args: ["push", "gcr.io/cloud-functions-estudo/ci-cd:$SHORT_SHA"]

    # us-central1
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "go-cloudrun",
        "--image",
        "gcr.io/cloud-functions-estudo/ci-cd:$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
